### ISSUE TITLE
when filtering by tag, link to second page is not formed

### ISSUE THREAD

**Issue by oshipka** [YuriyLisovskiy/OOA_Team_XAEA#10]
When sending a request to page 2, receiving 404 instead of 200

https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f87a6213ab96854ffa02a72eefd3cd9f8ceb0b76/StudArt/tests/artwork/views/test_ArtworksAPIView.py#L40-L42
https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f87a6213ab96854ffa02a72eefd3cd9f8ceb0b76/StudArt/tests/artwork/views/test_ArtworksAPIView.py#L47-L49

**Comment by YuriyLisovskiy** [comment]
Here is the same problem that I mentioned in the #11 issue.

**Comment by YuriyLisovskiy** [comment]
https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f87a6213ab96854ffa02a72eefd3cd9f8ceb0b76/StudArt/tests/artwork/views/test_ArtworksAPIView.py#L46-L51

In this test, you need to retrieve either 2 columns or check in the last assert that response gives you 3 results where the last list is empty.
