### ISSUE TITLE
When attempting to get answers to comment, request returns comments of parent artwork

### ISSUE THREAD

**Issue by oshipka** [YuriyLisovskiy/OOA_Team_XAEA#16]
https://github.com/YuriyLisovskiy/OOA_Team_XAEA/blob/f00ddb611253f8aa33a7d1c2014f80f6c9a71fb6/StudArt/tests/comment/views/test_CommentsAPIView.py#L19

**Comment by YuriyLisovskiy** [comment]
Fixed and will be added in `patch-5` soon.
